### ISSUE TITLE
Index out of range

### ISSUE THREAD

**Issue by BlackB846** [TheAxeDude/ZiniGo#18]
Hi,

I just came across the following error:

Starting the application...
panic: runtime error: index out of range [2] with length 0

goroutine 1 [running]:
main.GetInitialToken(0x945980, 0xc0000ce008, 0xc0000cb3e8, 0x1)
        C:/projects/ZiniGo/Grabazine.go:247 +0x267
main.main()
        C:/projects/ZiniGo/Grabazine.go:72 +0x3af

I currently have 531 magazines in my library - is there a limitation?

Thanks.

**Comment by Prizm4** [comment]
I get the same error. I only have one magazine in Zinio.

```
C:\zinigo>zinigo
Config file loaded
Username taken from config file
password taken from config file
chromepath taken from config file
Starting the application...
panic: runtime error: index out of range [2] with length 0

goroutine 1 [running]:
main.GetInitialToken(0x945980, 0xc000006018, 0xc00007f3e8, 0x1)
        C:/projects/ZiniGo/Grabazine.go:247 +0x267
main.main()
        C:/projects/ZiniGo/Grabazine.go:72 +0x3af
```

**Comment by nhand42** [comment]
Code is looking for a JWT (auth token)  in the HTML which isn’t there anymore. Looks like Zinio has changed their login process. Somebody will have to wire capture the latest Zinio desktop app to find the new URL they’re using.

**Comment by TheAxeDude** [comment]
Hi there, I will try take a look at this ASAP, hopefully they havent changed too much :)

**Comment by TheAxeDude** [comment]
I took a quick look, they've changed quite a bit - I'll try get a new working version ASAP.

**Comment by TheAxeDude** [comment]
Hi there,

I've published an updated version, using their new login mechanisms. https://github.com/TheAxeDude/ZiniGo/tree/master/built 

Please let me know if you have any issues?

**Comment by nhand42** [comment]
New version works for me on Linux/amd64. Can I also say thank you for your work on this program. It really is awesome.

**Comment by BlackB846** [comment]
Unlike the previous versions, this one will not launch under Windows 10

**Comment by TheAxeDude** [comment]
@BlackB846  I've rebuilt the windows exe (and tested). Sorry about that!

**Comment by BlackB846** [comment]
Thank you very much - works perfectly under current Win 10

**Comment by ZalakainTheOne** [comment]
Works fine, thanks!

**Comment by SR-G** [comment]
Surprinsigly i can't launch the latest binary under Linux : 
```
./Zinigo_Linux_AMD64 
zsh: exec format error: ./Zinigo_Linux_AMD64
```
and indeed when opening it with an HEX editor, he header does not contain the expected ELF first bytes ...

In fact i think both files are MAC versions : 
```
cksum Zinigo*
520078227 11627440 Zinigo_Linux_AMD64
520078227 11627440 Zinigo_Macos_AMD64
```
